paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos de la DB
      tags:
        - Products
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Token de autenticacion
          schema:
            type: string
      responses:
        "200":
          description: "Un listado de productos"
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: products
                  products:
                    type: array
                    items:
                      $ref: "#components/schemas/Product"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

    post:
      summary: Crear un producto
      tags:
        - Products
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Token de autenticacion
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto añadido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product added
                  newProduct:
                    type: object
                    $ref: "#components/schemas/Product"
        "400":
          description: Codigo ya existente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product code already exists
        "500":
          description: Error al crear el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error adding product

  /api/products/{pid}:
    put:
      summary: Actualizar un producto
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto a actualizar
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          description: Token de autenticacion
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Product updated
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "201":
          description: Producto actualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product updated
                  producto:
                    type: object
                    $ref: "#components/schemas/Product"
        "403":
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden: You don't have permission to update this product"
        "500":
          description: Error al actualizar el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error updating product

    delete:
      summary: Eliminar un producto
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto a eliminar
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          description: Token de autenticacion
          schema:
            type: string

      responses:
        "200":
          description: Producto eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product deleted
                  producto:
                    type: object
                    $ref: "#components/schemas/Product"
        "403":
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden: You don't have permission to delete this product"
        "404":
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
        "500":
          description: Error al eliminar el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error deleting product
